language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean package -DskipTests

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken="${COVERALLS_TOKEN}"
