language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -u root --password="" < src/test/resources/travisci.sql

branches:
  only:
    - master

script: mvn clean package -DskipTests

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken="${COVERALLS_TOKEN}"
